version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      # - checkout
      # - run:
      #     name: Installing AWS CLI
      #     command: |
      #       sudo apt-get update
      #       sudo apt install python3-pip
      #       sudo pip3 install awsebcli --upgrade
      # - run: npm install && npm run build
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - .
      - checkout
      # - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRETE_KEY
          from: ./build
          to: 's3://my-hosted-conten/prefix'
      - run: aws s3 sync ./build s3://my-hosted-conten
  deploy:
    machine:
        image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./build s3://my-hosted-conten
    

workflows:
  build_test_deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build