version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Configure AWS Access Key ID
          command: |
            aws configure set aws_access_key_id \
            $AWS_ACCESS_KEY \
            echo "Print the value for $AWS_ACCESS_KEY $AWS_SECRETE_KEY"

      - run:
          name: Configure AWS Secret Access Key
          command: |
            aws configure set aws_secret_access_key \
            $AWS_SECRETE_KEY \

      - run:
          name: Configure AWS default region
          command: |
            aws configure set region $AWS_REGION \
     
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run: npm install && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    machine:
        image: ubuntu-2004:202010-01
    steps:
      - attach_workspace:
          at: .
      - checkout
      - run: aws s3 sync ./build s3://my-hosted-conten
    

workflows:
  build_test_deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build